services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: api-java-docker
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}  # Directly set the URL
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}  # Reference environment variable
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}  # Reference environment variable
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Reference environment variable
      POSTGRES_USER: ${POSTGRES_USER}  # Reference environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Reference environment variable
    ports:
      - "5432:5432"