services:
  app:
    build: .
    container_name: sales-api-java
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sales-network
  db:
    image: "postgres:13.1-alpine"
    container_name: sales-db-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge

volumes:
  postgres_data:
